/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.muspellheim.todos.app;

import static de.muspellheim.todos.app.MessageUtils.getMessage;
import static de.muspellheim.todos.utilities.StringUtils.join;
import static de.muspellheim.todos.utilities.StringUtils.split;

import de.muspellheim.todos.list.LinkedList;
import org.apache.commons.text.WordUtils;

public class App {
  public static void main(String[] args) {
    LinkedList tokens;
    tokens = split(getMessage());
    String result = join(tokens);
    System.out.println(WordUtils.capitalize(result));
  }
}
